# Generated by Django 5.0.7 on 2024-08-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_num',
            new_name='roll_no',
        ),
    ]
