# Generated by Django 5.0.7 on 2024-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_rename_roll_num_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('contry', models.CharField(max_length=20)),
            ],
        ),
    ]
