# Generated by Django 5.0.7 on 2024-08-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contry',
            new_name='country',
        ),
    ]
